# Generated by Django 4.2.5 on 2023-09-21 11:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=128)),
                ('isbn', models.CharField(max_length=13)),
                ('publishel', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('number_of_available', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('must_return_date', models.DateTimeField(default=datetime.datetime(2023, 10, 1, 11, 46, 11, 815691, tzinfo=datetime.timezone.utc))),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lib_manage.book')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('tell', models.CharField(max_length=11)),
                ('date', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(default=datetime.datetime(2023, 9, 21, 11, 46, 11, 815691, tzinfo=datetime.timezone.utc))),
                ('borrowed_book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lib_manage.borrowedbook')),
            ],
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_manage.person'),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='return_book',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lib_manage.returnbook'),
        ),
    ]
