# Generated by Django 4.2.5 on 2023-09-21 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='must_return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 13, 8, 58, 261139, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='returnbook',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 13, 8, 58, 261139, tzinfo=datetime.timezone.utc)),
        ),
    ]
