# Generated by Django 4.2.5 on 2023-10-28 18:52

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lib_manage', '0002_alter_borrowedbook_must_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='must_return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 18, 52, 8, 57696, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='returnbook',
            name='return_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
